name: Linux CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build wheel
        run: python3 -m pip wheel .

      - name: Install wheel
        run: python3 -m pip install *.whl

      - name: Install test requirements
        run: python3 -m pip install -r test/requirements.txt

      - name: Run tests
        run: python3 -m pytest test/