name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  

jobs:
  build-and-test:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build wheel
        run: python3 -m pip wheel .

      - name: Install wheel
        run: python3 -m pip install (get-item .\*.whl)

      - name: Install test requirements
        run: python3 -m pip install -r test/requirements.txt

      - name: Run tests
        run: python3 -m pytest test/
